// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roboline.Persistence;

#nullable disable

namespace Roboline.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241016193040_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roboline.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest model smartphone",
                            Name = "Smartphone",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 1500.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Lightweight tablet",
                            Name = "Tablet",
                            Price = 600.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Professional digital camera",
                            Name = "Camera",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Best-selling fiction novel",
                            Name = "Fiction Novel",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Comprehensive science textbook",
                            Name = "Science Textbook",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Life of famous historical figure",
                            Name = "Historical Biography",
                            Price = 25.75m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Popular children's storybook",
                            Name = "Children's Book",
                            Price = 15.49m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Recipes from world-renowned chefs",
                            Name = "Cookbook",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Casual cotton t-shirt",
                            Name = "Men's T-Shirt",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Elegant evening dress",
                            Name = "Women's Dress",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Winter jacket for kids",
                            Name = "Children's Jacket",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Denim jeans for men",
                            Name = "Men's Jeans",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Stylish summer hat",
                            Name = "Women's Hat",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "High-speed kitchen blender",
                            Name = "Blender",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Compact microwave oven",
                            Name = "Microwave Oven",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Non-stick cookware set",
                            Name = "Cookware Set",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Four-slice toaster",
                            Name = "Toaster",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "Creative building block set",
                            Name = "Kids Building Blocks",
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("Roboline.Domain.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets.",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All genres of books and literature.",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel for men, women, and children.",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Appliances and utensils for home.",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Toys for kids of all ages.",
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("Roboline.Domain.Product", b =>
                {
                    b.HasOne("Roboline.Domain.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
