services:
  backend:
    container_name: "medical.backend"
    build:
      context: .
      dockerfile: MedicalTestTask/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql_server,1433;Database=MedicalDB;User Id=sa;Password=strong@Passw0rd;
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "medical.mssql"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=strong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql

volumes:
  mssql_data: