// <auto-generated />
using System;
using GrpcServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313162004_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcServer.Models.GameTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("GameTransactions");
                });

            modelBuilder.Entity("GrpcServer.Models.MatchHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("FirstUserChoice")
                        .HasColumnType("integer");

                    b.Property<long?>("FirstUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SecondUserChoice")
                        .HasColumnType("integer");

                    b.Property<long?>("SecondUserId")
                        .HasColumnType("bigint");

                    b.Property<double>("Stake")
                        .HasColumnType("double precision");

                    b.Property<long?>("WinnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FirstUserId");

                    b.HasIndex("SecondUserId");

                    b.HasIndex("WinnerId");

                    b.ToTable("MatchHistories");
                });

            modelBuilder.Entity("GrpcServer.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GrpcServer.Models.GameTransaction", b =>
                {
                    b.HasOne("GrpcServer.Models.User", "Receiver")
                        .WithMany("ReceiverTransactions")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrpcServer.Models.User", "Sender")
                        .WithMany("SenderTransactions")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GrpcServer.Models.MatchHistory", b =>
                {
                    b.HasOne("GrpcServer.Models.User", "FirstUser")
                        .WithMany("MatchHistoriesFirstUser")
                        .HasForeignKey("FirstUserId");

                    b.HasOne("GrpcServer.Models.User", "SecondUser")
                        .WithMany("MatchHistoriesSecondUser")
                        .HasForeignKey("SecondUserId");

                    b.HasOne("GrpcServer.Models.User", "WinnerUser")
                        .WithMany("WonMatches")
                        .HasForeignKey("WinnerId");

                    b.Navigation("FirstUser");

                    b.Navigation("SecondUser");

                    b.Navigation("WinnerUser");
                });

            modelBuilder.Entity("GrpcServer.Models.User", b =>
                {
                    b.Navigation("MatchHistoriesFirstUser");

                    b.Navigation("MatchHistoriesSecondUser");

                    b.Navigation("ReceiverTransactions");

                    b.Navigation("SenderTransactions");

                    b.Navigation("WonMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
